packages:
  - 'BeeVoice'
  - 'Hive'
  - 'HivePlugins'
  - 'HoneyBoard'
  - 'HoneyFlow'
  - 'HiveExtension'
  - 'HiveMind'
  - 'Nectar'
  - 'Nectar/nectar-mcp'
  - 'QueenBee'
  - 'TaskComb'
  - 'WorkerBees'
  - 'WorkHive'
  - 'landing-page'
